
version: '3.9'
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./storage/results:/data/results
      - ./storage/scripts:/data/scripts


  worker-node:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./storage/results:/data/results
      - ./storage/scripts:/data/scripts
    command: >
      sh -c "
        rm -rf /data/scripts/node_modules &&
        ln -s /app/node_modules /data/scripts/node_modules &&
        node src/workers/node/worker.js
      "

  python-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./storage/results:/data/results
      - ./storage/scripts:/data/scripts
    ports:
      - "9000:9000"       # <-- IMPORTANT
  
  worker-batch-row:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    env_file: .env
    volumes:
      - ./storage/results:/data/results
      - ./storage/uploads:/data/uploads
      - ./storage/scripts:/data/scripts
    depends_on:
      - redis
    command: >
      sh -c "
        echo 'ðŸŸ¦ Creating symlink for node_modules...' &&
        rm -rf /data/scripts/node_modules &&
        ln -s /app/node_modules /data/scripts/node_modules &&
        echo 'ðŸŸ© Symlink created. Starting worker...' &&
        node src/workers/node/batch_row_worker.js
      "
    environment:
      - REDIS_URL=redis://redis:6379
      - WORKER_CONCURRENCY=10
      - WORKER_MAX_CHILDREN=1000
