version: '3.9'
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./storage/results:/data/results
      - ./storage/scripts:/data/scripts


  worker-node:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    env_file: .env
    depends_on:
      - redis
    volumes:
    - ./storage/results:/data/results
    - ./storage/scripts:/data/scripts

  worker-python:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./storage/results:/data/results
      - ./storage/scripts:/data/scripts
  worker-batch-row:
    build:
      context: .
      dockerfile: docker/Dockerfile.node   # <-- this is the correct Dockerfile
    command: node src/workers/node/batch_row_worker.js
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./storage/results:/data/results
      - ./storage/uploads:/data/uploads
      - ./storage/scripts:/data/scripts
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - WORKER_CONCURRENCY=10
      - WORKER_MAX_CHILDREN=1000