version: '3.9'
services:
  db:
    image: postgres:16
    container_name: elweb-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: eluser
      POSTGRES_PASSWORD: elpass
      POSTGRES_DB: elweb
    volumes:
      - ./storage/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: elweb-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
